baseURL = "https://sindustries.net/"
title = "Sindustries"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Syndariel" # title for frontpage, may include image
copyright = "Storm S"
description = 'Purveyor of Shitposting'
#startbuttonText = "Activate"
#startbuttonLink = "#"
body_is_markdown = true
custom_css = "css/sindustries.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = false
title = 'Contact Me but coolerer'
body = '''
Something about vidjagams
'''

[[params.one.icon]]
icon = "solid fa-diamond"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = false

[[params.two.section]]
img = "img/pic01.jpg"
img_alt = "blurry background: white/grey"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Tortor dolore feugiat<br />elementum magna'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'About Me'
body = '''
This is where I will put information about random interests, hobies, education, etc. etc.
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Education"
body = "This is where I will put information about my education"

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Hobbies"
body = "This is where I will put information about my hobies"

[[params.three.feature]]
icon = "solid fa-code"
title = "InfoSec Stuff"
body = "This is where I will put information about my interests within this field"

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "Placeholder 1"
body = "Placeholder 1.1"

[[params.three.feature]]
icon = "fa-heart"
title = "Placeholder 2"
body = "Placeholder 2.2"

[[params.three.feature]]
icon = "fa-flag"
title = "Placeholder 3"
body = "Placeholder 3.3"

[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
#phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
#email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = "Syndustries"
facebook = ""
youtube = ""
instagram = ""
dribble = ""
linkedin = "https://www.linkedin.com/in/stormstrange02"

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"
